[user]
name = "Christian Leopoldseder"
email = "christian@leopoldse.dev"

[aliases]
lg = ["log", "-r", "(@ | ancestors(immutable_heads().., 2) | trunk()) | remote_bookmarks()"]

[revsets]
immutable_heads = "builtin_immutable_heads() | remote_bookmarks()"

[colors]
# Highlight hunks with background
"diff removed token" = { underline = false }
"diff added token" = { underline = false }
